adding main.py file
lanaHamayel5/Creating-Simple-Quiz-Using-Python pull request #1
Opened 2024-07-30 13:07 UTC by lanaHamayel5

2024-07-30 13:35 UTC, WaseemSayara requested changes
First of all, very nice job, it works perfectly, and i really like your attention to details.
But I would like you to make some modifications,

1. Use multiple choice [1) .. , 2)..., 3)...] ask the user to enter a number.
2. use `f __name__ == “__main__”:` read more here: https://www.geeksforgeeks.org/what-does-the-if-__name__-__main__-do/

2024-07-30 13:35 UTC, WaseemSayara commented on main.py
> +def checkAnswer(enteredAnswer, correctAnswer):
The function name should be `check_answer`

2024-07-30 13:35 UTC, WaseemSayara commented on main.py
> +        score -= 1  # Decrease score for a wrong answer
This is a logical error, if the answer is wrong then we do nothing

2024-07-30 13:35 UTC, WaseemSayara commented on main.py
> +    numOfquestions+=1
`num_of_questions` or `questions_count`

2024-08-01 07:18 UTC, WaseemSayara reviewed
Much cleaner, but we can still make better

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +values = [4, 1, 1, 1, 3, 4, 1]
This is not needed
please find another way to check for the result.
Hint: compare values

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +        return "wrong"
you can do something better ans easier here

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +    # print(data)
remove these two lines

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +    j=1
use meaningful name

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +        questions_count+=1
Code duplication, you make something more dynamic without code duplication.

2024-08-01 07:18 UTC, WaseemSayara commented on main.py
> +    main()
Whener you see this red icon, it means there should be an empty line at the end of the file

2024-08-01 10:21 UTC, WaseemSayara reviewed
Very nice, added few comments for better readabilty and to make it more dynamic

2024-08-01 10:21 UTC, WaseemSayara commented on data.json
> +
only one line is enough

2024-08-01 10:21 UTC, WaseemSayara commented on main.py
> +
keep 1 line

2024-08-01 10:21 UTC, WaseemSayara commented on main.py
> +    for question_type in ['sport', 'maths']:
this can be replaced with 
`for question_type in data['quiz']:`
This is more dynamic

2024-08-01 10:21 UTC, WaseemSayara commented on main.py
> +        for q_key, q_value in data['quiz'][question_type].items():
`q_key` is not used

2024-08-01 10:21 UTC, WaseemSayara commented on main.py
> +        return "wrong"
lets compare strings, and make the function returm bool: (Troe or False) and increase the score in the main.
this way we get rid of the `global score`, and make it simpler.

2024-08-01 10:21 UTC, WaseemSayara commented on main.py
> +            print("Invalid input. Please enter a number.")
Can we make it more dynamic, for example what if one of the questions has only two options?

2024-08-01 13:44 UTC, waseem-sayara approved these changes

2024-08-01 13:45 UTC, WaseemSayara approved these changes

2024-08-01 13:47 UTC, merged